CREATE TABLE products (
    id INT PRIMARY KEY AUTO_INCREMENT,
     brand VARCHAR(255),
     name VARCHAR(255),
     release_date DATE,
     size VARCHAR(50),
     price DECIMAL(10, 2),
     url VARCHAR(255)
);


INSERT INTO products (brand, name, release_date, price, url)
VALUES
    ('Nike', 'Jordan 11 Retro DMP Gratitude (2023)', '2023-11-14', '194', 'https://stockx.com/air-jordan-11-retro-dmp-defining-moments-2023'),
    ('Nike', 'Nike Kobe 6 Protro Reverse Grinch', '2023-12-16', '369 ', 'https://stockx.com/nike-kobe-6-protro-reverse-grinch'),
    ('UGG', 'UGG Tasman Slipper Palace Chestnut', '2023-12-01', '286', 'https://stockx.com/ugg-tasman-slipper-palace-chestnut'),
    ('Nike', 'Nike Air More Uptempo 96 Action Grape', '2022-08-27', '89', 'https://stockx.com/nike-air-more-uptempo-action-grape'),
    ('Lanvin', 'Lanvin Leather Curb White Ivory', '2021-07-01', '418', 'https://stockx.com/lanvin-leather-curb-white-ivory'),
    ('OFF-WHITE', 'OFF-WHITE Out Of Office OOO Low Tops For Walking White Black', '2021-06-01', '317', 'https://stockx.com/off-white-ooo-low-tops-for-walking-white-black-ss21'),
    ('Nike', 'Nike Dunk Low Photon Dust (Women\'s)', '2021-05-19', '86', 'https://stockx.com/nike-dunk-low-photon-dust-w'),
    ('adidas', 'adidas Yeezy Slide Slate Grey', '2023-08-18', '72', 'https://stockx.com/adidas-yeezy-slide-slate-grey'),
    ('UGG', 'UGG Tasman Slipper Chestnut (Women\'s)', '2021-11-01', '122', 'https://stockx.com/ugg-tasman-slipper-chestnut-w'),
    ('Nike', 'Nike Dunk Low Grey Fog', '2021-09-21', '86', 'https://stockx.com/nike-dunk-low-grey-fog'),
    ('UGG', 'UGG Classic Ultra Mini Boot Chestnut (Women\'s)', '2021-11-01', '97', 'https://stockx.com/ugg-classic-ultra-mini-chestnut-w'),
    ('adidas', 'adidas Campus 00s Core Black', '2023-02-17', '100', 'https://stockx.com/adidas-campus-00s-core-black'),
    ('Nike', 'Nike Dunk Low Retro White Black Panda', '2021-03-10', '93', 'https://stockx.com/nike-dunk-low-retro-white-black-2021'),
    ('UGG', 'UGG Tazz Slipper Chestnut (Women\'s)', '2021-11-01', '138', 'https://stockx.com/ugg-tazz-slipper-chestnut-w'),
    ('UGG', 'UGG Tasman Slipper Chestnut', '2020-03-14', '90', 'https://stockx.com/ugg-tasman-slipper-chestnut'),
    ('Nike', 'Nike Dunk Low Cacao Wow (Women\'s)', '2023-07-28', '97', 'https://stockx.com/nike-dunk-low-cacao-wow-womens'),
    ('Crocs', 'Crocs Classic Clog Lightning McQueen', '2021-04-27', '97', 'https://stockx.com/crocs-classic-clog-lightning-mcqueen'),
    ('adidas', 'adidas Campus 00s Grey White', '2023-03-01', '98', 'https://stockx.com/adidas-campus-00s-grey-white'),
    ('adidas', 'adidas Yeezy Slide Onyx (2022/2023)', '2022-03-07', '94', 'https://stockx.com/adidas-yeezy-slide-black-onyx'),
    ('adidas', 'adidas Yeezy Slide Slate Marine', '2023-08-11', '71', 'https://stockx.com/adidas-yeezy-slide-slate-marine'),
    ('UGG', 'UGG Tasman Slipper Black (Women\'s)', '2021-11-01', '117', 'https://stockx.com/ugg-tasman-slipper-black-w'),
    ('Nike', 'Nike Dunk Low Polar Blue', '2023-10-14', '88', 'https://stockx.com/nike-dunk-low-polar-blue'),
    ('UGG', 'UGG Tasman II Slipper Chesnut (Kids)', '2021-01-01', '72', 'https://stockx.com/ugg-tasman-ii-slipper-chesnut-kids'),
    ('UGG', 'UGG Tasman Slipper Black', '2020-03-14', '101', 'https://stockx.com/ugg-tasman-slipper-black'),
    ('Nike', 'Nike Dunk Low Retro White Black Panda (Women\'s)', '2021-03-10', '91', 'https://stockx.com/nike-dunk-low-white-black-2021-w'),
    ('Jordan', 'Jordan 4 Retro Red Cement', '2023-09-09', '193', 'https://stockx.com/air-jordan-4-retro-red-cement'),
    ('Nike', 'Nike Air Force 1 Low \'07 White', '2020-12-09', '80', 'https://stockx.com/nike-air-force-1-low-white-07'),
    ('adidas', 'adidas Yeezy Slide Bone (2022/2023 Restock)', '2022-05-31', '133', 'https://stockx.com/adidas-yeezy-slide-bone-2022'),
    ('Nike', 'Nike Dunk Low SP St. John\'s (2020/2023)', '2023-10-24', '100', 'https://stockx.com/nike-dunk-low-st-johns-2020'),
    ('Nike', 'Nike Dunk Low Triple Pink (GS)', '2022-06-01', '99', 'https://stockx.com/nike-dunk-low-triple-pink-gs'),
    ('Crocs', 'Crocs Classic Clog Mater', '2023-10-17', '70', 'https://stockx.com/crocs-classic-clog-mater'),
    ('UGG', 'UGG Disquette Slipper Chestnut (Women\'s)', '2021-01-01', '122', 'https://stockx.com/ugg-disquette-slipper-chestnut-w'),
    ('Jordan', 'Jordan 1 Low Wolf Grey (Women\'s)', '2021-07-20', '102', 'https://stockx.com/air-jordan-1-low-wolf-grey-w'),
    ('Jordan', 'Jordan 4 Retro SE Craft Medium Olive', '2023-11-18', '180', 'https://stockx.com/air-jordan-4-retro-se-craft-medium-olive'),
    ('Nike', 'Nike KD 16 Aunt Pearl', '2023-10-27', '171', 'https://stockx.com/nike-kd-16-aunt-pearl'),
    ('New Balance', 'New Balance 2002R Protection Pack Rain Cloud', '2021-08-20', '134', 'https://stockx.com/new-balance-m2002-protection-pack-rain-cloud'),
    ('Nike', 'Nike Dunk Low Retro White Black Panda (GS)', '2021-03-10', '74', 'https://stockx.com/nike-dunk-low-retro-white-black-gs'),
    ('adidas', 'adidas Yeezy Boost 350 V2 Bone', '2022-03-21', '186', 'https://stockx.com/adidas-yeezy-boost-350-v2-bone'),
    ('adidas', 'adidas Yeezy Slide Granite', '2023-08-25', '69', 'https://stockx.com/adidas-yeezy-slide-granite'),
    ('adidas', 'adidas Yeezy Foam RNR Carbon', '2023-08-07', '108', 'https://stockx.com/adidas-yeezy-foam-rnr-carbon'),
    ('Jordan', 'Nike Dunk Low Diffused Taupe (Women\'s)', '2023-12-01', '116', 'https://stockx.com/nike-dunk-low-diffused-taupe-womens'),
    ('UGG', 'UGG Classic Ultra Mini Platform Boot Chestnut (Women\'s)', '2022-10-10', '140', 'https://stockx.com/ugg-classic-ultra-mini-platform-chestnut-w'),
    ('New Balance', 'New Balance 550 White Green', '2021-06-24', '91', 'https://stockx.com/new-balance-550-white-green'),
    ('UGG', 'UGG Tazz Slipper Sand (Women\'s)', '2023-11-24', '163', 'https://stockx.com/ugg-tazz-slipper-sand-womens'),
    ('Jordan', 'Jordan 3 Retro Doernbecher Hugo', '2023-12-02', '266', 'https://stockx.com/air-jordan-3-retro-doernbecher-hugo'),
    ('Nike', 'Nike Dunk Low Smoke Grey Gum 3M Swoosh', '2023-10-03', '121', 'https://stockx.com/nike-dunk-low-smoke-grey-gum-3m-swoosh'),
    ('UGG', 'UGG Tasman Slipper Mustard Seed (Women\'s)', '2023-09-01', '133', 'https://stockx.com/ugg-tasman-slipper-mustard-seed-womens'),
    ('Jordan', 'Jordan 1 Retro High OG UNC Toe', '2023-07-22', '173', 'https://stockx.com/air-jordan-1-high-og-unc-toe'),
    ('adidas', 'adidas Samba OG Cloud White Core Black', '2018-01-01', '76', 'https://stockx.com/adidas-samba-og-cloud-white-core-black');